config/routes.rb
Rails.application.routes.draw do
  get 'stores/new'

 
  get 'home/map'  #map페이지 보기 위해 임시로 만들어 놓는 곳
  get 'home/map/:store_category', to: 'home#map'
  
  get 'stores/index', to: 'stores#index'
  get 'stores/index/:store_name', to: 'stores#index'
  get 'stores/result', to: 'stores#result'
 

  devise_for :users
  
  root 'home#index'
  resources :home
  resources :users do
    resources :stores
  end
  resources :stores  #이건 store체크용 resoureces 라우팅

end

app/models/store.rb
class Store < ActiveRecord::Base
    belongs_to :user
    
    def self.search(key)
        where("store_name LIKE ?", "%#{key}%")
    end
    
    has_attached_file :photo, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/dahong_0.png"
    validates_attachment_content_type :photo, :content_type => /^image\/(jpeg|png|gif|jpg|tiff)$/
    validates_attachment_size :photo, :in => 0..20.megabytes
    
    has_attached_file :photo2, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/dahong_0.png"
    validates_attachment_content_type :photo2, :content_type => /^image\/(jpeg|png|gif|jpg|tiff)$/
    validates_attachment_size :photo2, :in => 0..20.megabytes
      
    has_attached_file :photo3, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/dahong_0.png"
    validates_attachment_content_type :photo3, :content_type => /^image\/(jpeg|png|gif|jpg|tiff)$/
    validates_attachment_size :photo3, :in => 0..20.megabytes
 
 
    validates :store_name, presence: true, length: { minimum: 1, message: "상호명을 입력해주세요"}
    validates :address, presence: true, length: { minimum: 1, message: "주소를 입력해주세요"}
    validates :contact, presence: true, length: { minimum: 1, message: "연락처를 입력해주세요"}
    validates :short_content, presence: true, length: { minimum: 1, message: "한줄소개를 입력해주세요"}
    validates :detail_content, presence: true, length: { minimum: 1, message: "상세소개를 입력해주세요"}
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable # :confirmable
         
  has_many :stores
  
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def map
    @category = params[:store_category]
    @test2 = Store.where(store_category: @category)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @category = params[:store_category]
    @stores = Store.where(store_category: @category)
 
  end
  def result
    @test = params[:store][:store_name]
    if @test.empty? || @test.nil?
      flash[:fail] = "빈칸없이 입력해주세요!"
      redirect_to :back
    else
      @results = Store.search(@test)
    end
  end

  def new
    @store = Store.new
  end
  
  def create
    @store = Store.new(store_params)
    
    if @store.save
      redirect_to @store
    else
      render "new"
    end
  end
  
  def edit
    @store = Store.find(params[:id])
    unless @store.user_id == current_user.id
      flash[:fail] = "본인이 작성한 글이 아닙니다."
      redirect_to :back
    end
  end
  def update
     @store = Store.find(params[:id])

  if @store.update(store_params)
    redirect_to @store
  else
    render 'edit'
  end
  end
  
  def destroy
    @store = Store.find(params[:id])
      if @store.user_id == current_user.id
        
        @store.destroy
        redirect_to '/'
      else
      flash[:fail] = "본인이 작성한 글이 아닙니다."
      redirect_to :back
      end
  end
  
  def show
    @store = Store.find(params[:id])
  end  
  private
    def store_params
      params.require(:store).permit(:store_name, :store_category,
                                    :address, :detail_address,
                                    :contact, :short_content,
                                    :detail_content, :photo,:photo2,:photo3,:user_id)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/index.html.erb
<styles>
  <link rel="stylesheet" href="/assets/home_index.scss">   
</styles>


<article class = "Main_article">
  <div class="row y-margin-edit">
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
      <div class="dahong-category-border">  

        
        <%= link_to home_map_path(store_category: '식당') do %> 
   
            
         
          <div class="dahong-category-border-inner" id="restaurants">
            <div class="dahong-category-inner-content">
              <!--모바일-->
              <div class="d-block d-xs-block d-sm-none d-md-none">
                <p class="category-icon"><i class="fas fa-utensils  "></i></p>
                <p class="category-text">식당</p>
              </div>
              <!--태블릿-->
              <div class="d-none d-sm-block d-md-none d-lg-none">
                <p class="category-icon"><i class="fas fa-utensils  "></i></p>
                <p class="category-text" >식당</p>
              </div>
              <!--데스크탑-->
              <div class="d-none d-sm-block d-md-block">
                <p class="category-icon"><i class="fas fa-utensils  "></i></p>
                <p class="category-text" >식당</p>
              </div>
            </div>
          </div>
      
         <% end %>
      </div>
    </div>
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
      <div class="dahong-category-border">
        <%= link_to home_map_url(store_category: "카페") do %>
          <div class="dahong-category-border-inner" id="coffee">
            <div class="dahong-category-inner-content">
              <!--모바일-->
              <div class="d-block d-xs-block d-sm-none d-md-none">
                <p class="category-icon"><i class="fas fa-coffee  "></i></p>
                <p class="category-text">카페</p>
              </div>
              <!--태블릿-->
              <div class="d-none d-sm-block d-md-none d-lg-none">
                <p class="category-icon"><i class="fas fa-coffee  "></i></p>
                <p class="category-text" >카페</p>
              </div>
              <!--데스크탑-->
              <div class="d-none d-sm-block d-md-block">
                <p class="category-icon"><i class="fas fa-coffee  "></i></p>
                <p class="category-text" >카페</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
      <div class="dahong-category-border">
        <%= link_to home_map_url(store_category: "옷가게") do %>
          <div class="dahong-category-border-inner" id="clothes">
            <div class="dahong-category-inner-content">
              <!--모바일-->
              <div class="d-block d-xs-block d-sm-none d-md-none">
                <p class="category-icon"><i class="fas fa-tshirt  "></i></p>
                <p class="category-text">옷가게</p>
              </div>
              <!--태블릿-->
              <div class="d-none d-sm-block d-md-none d-lg-none">
                <p class="category-icon"><i class="fas fa-tshirt  "></i></p>
                <p class="category-text" >옷가게</p>
              </div>
              <!--데스크탑-->
              <div class="d-none d-sm-block d-md-block">
                <p class="category-icon"><i class="fas fa-tshirt  "></i></p>
                <p class="category-text" >옷가게</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
      <div class="dahong-category-border">
        <%= link_to home_map_url(store_category: "술집") do %>
          <div class="dahong-category-border-inner" id="bars">
            <div class="dahong-category-inner-content">
              <!--모바일-->
              <div class="d-block d-xs-block d-sm-none d-md-none">
                <p class="category-icon"><i class="fas fa-beer  "></i></p>
                <p class="category-text">술집</p>
              </div>
              <!--태블릿-->
              <div class="d-none d-sm-block d-md-none d-lg-none">
                <p class="category-icon"><i class="fas fa-beer  "></i></p>
                <p class="category-text" >술집</p>
              </div>
              <!--데스크탑-->
              <div class="d-none d-sm-block d-md-block">
                <p class="category-icon"><i class="fas fa-beer  "></i></p>
                <p class="category-text" >술집</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
      <div class="dahong-category-border">
        <%= link_to home_map_url(store_category: "스터디룸") do %>
          <div class="dahong-category-border-inner" id="studyrooms">
            <div class="dahong-category-inner-content">
              <!--모바일-->
              <div class="d-block d-xs-block d-sm-none d-md-none">
                <p class="category-icon"><i class="fas fa-pencil-alt  "></i></p>
                <p class="category-text">스터디룸</p>
              </div>
              <!--태블릿-->
              <div class="d-none d-sm-block d-md-none d-lg-none">
                <p class="category-icon"><i class="fas fa-pencil-alt  "></i></p>
                <p class="category-text" >스터디룸</p>
              </div>
              <!--데스크탑-->
              <div class="d-none d-sm-block d-md-block">
                <p class="category-icon"><i class="fas fa-pencil-alt  "></i></p>
                <p class="category-text" >스터디룸</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-6 col-md-4 col-lg-4 y-padding-edit">
        <div class="dahong-category-border">
          <%= link_to home_map_url(store_category: "기타") do %>
            <div class="dahong-category-border-inner" id="etc">
              <div class="dahong-category-inner-content">
                <!--모바일-->
                <div class="d-block d-xs-block d-sm-none d-md-none">
                  <p class="category-icon"><i class="fas fa-ellipsis-h  "></i></p>
                  <p class="category-text">기타</p>
                </div>
                <!--태블릿-->
                <div class="d-none d-sm-block d-md-none d-lg-none">
                  <p class="category-icon"><i class="fas fa-ellipsis-h  "></i></p>
                  <p class="category-text" >기타</p>
                </div>
                <!--데스크탑-->
                <div class="d-none d-sm-block d-md-block">
                  <p class="category-icon"><i class="fas fa-ellipsis-h  "></i></p>
                  <p class="category-text" >기타</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</article>
<footer class="bg-light">
  <p class="dahong-team-name">Team DAHONG</p>
  <p class="dahong-team-members">강동기 박효빈 장치훈 최예은</p>
</footer>

app/views/home/map.html.erb
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title> 다홍여지도 </title>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=rjesxd516o"></script>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=rjesxd516o&submodules=geocoder"></script>
</head>
<body>
<link rel="stylesheet" href="/assets/home_map.css.scss">
<div class="dahong-map-list-title"><%= @category %></div>
<%= link_to stores_url(store_category: @category) do %>
    <button class="dahong-map-list-change-btn">리스트 보기</button>
<% end %>

<div class="dahong-float-clear"></div>

<div class="dahong-map-list-wrap">
<div class="row dahong-map-list-row">
    <div class="col-md-12 dahong-map-layout">

      <!-- 요기서 부터 네이버 지도 API 본문 -->
      <div id="map" style="width:100%;height:500px;"></div><br>

      <script>

      // 지도에 표시한 UI들 및 옵션



      var mapOptions = {
          center: new naver.maps.LatLng(35.2330218, 129.0798455),
          zoom: 10,
          zoomControl: true,
          zoomControlOptions: {
            style: naver.maps.ZoomControlStyle,
            position: naver.maps.Position.LEFT_CENTER

           },
          mapTypeControl: true
      };

      var map = new naver.maps.Map('map', mapOptions);



      // // 사용자 현재 위치 추적
      var infowindow = new naver.maps.InfoWindow();

      function onSuccessGeolocation(position) {
          var location = new naver.maps.LatLng(position.coords.latitude,
                                              position.coords.longitude);

          map.setCenter(location); // 얻은 좌표를 지도의 중심으로 설정
          map.setZoom(7); // 지도의 줌 레벨을 변경.... 몇으로 하는게 보기 쉬울까..? maybe 12?

          infowindow.setContent('<div style="padding:20px;">' + 'Me' + '</div>');

          infowindow.open(map, location);
          console.log('Coordinates: ' + location.toString());

      }

      function onErrorGeolocation() {
          var center = map.getCenter();

          infowindow.setContent('<div style="padding:20px;">' +
              '<h5 style="margin-bottom:5px;color:#f00;">Geolocation failed!</h5>'+ "latitude: "+ center.lat() +"<br />longitude: "+ center.lng() +'</div>');

          infowindow.open(map, center);
      }

      $(window).on("load", function() {
          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(onSuccessGeolocation, onErrorGeolocation);
          } else {
              var center = map.getCenter();
              infowindow.setContent('<div style="padding:20px;"><h5 style="margin-bottom:5px;color:#f00;">위치를 허용해 주십시오</h5></div>');
              infowindow.open(map, center);
          }
      });



     // 사용자 위치로 이동하는 컨트롤

      var locationBtnHtml = '<a href="#"><span><img src="/assets/myloc.png" class="dahong-myloc-logo"/></span></a>';

      var customControl = new naver.maps.CustomControl(locationBtnHtml, {
          position: naver.maps.Position.LEFT_TOP
      });

      customControl.setMap(map);

      var domEventListener = naver.maps.Event.addDOMListener(customControl.getElement(), 'click', function() {
          map.setCenter(navigator.geolocation.getCurrentPosition(onSuccessGeolocation));
      });

      map.setCursor('pointer');



      <% @test2.each do |store| %>

           naver.maps.Service.geocode({
                address: '<%= store.address %>'
            }, function(status, response) {
                if (status === naver.maps.Service.Status.ERROR) {
                    return alert('Something Wrong!');
                }

                var item = response.result.items[0],
                    addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]',
                    point = new naver.maps.Point(item.point.x, item.point.y);

               var marker = new naver.maps.Marker({
                  map: map,
                  position: point,
                  title: '<%= store.address %>',
                  icon: {
                            url: '/images/dahong_main2.png',
                            size: new naver.maps.Size(20, 30),
                            anchor: new naver.maps.Point(10, 30)},
                  zIndex: 100
               });


                var contentString = [


                    '<div class = "dahong-map-card">'+
                      '<%= link_to  store_path(store) do %>'+
                      '<div class = "dahong-map-photo"><%= image_tag store.photo.url(:thumb) %></div>'+
                      '<div class = "dahong-map-storename" ><%= store.store_name %></div>'+
                      '<div class = "dahong-map-address"><%= store.address %></div>'+
                      '<div class = "dahong-map-contact"><%= store.contact %></div>'+
                      '<div class = "dahong-map-content"><%= store.short_content %></div>'+

                      '<% end %>'+

                    '</div>'

                ].join('');

               var infoWindow2 = new naver.maps.InfoWindow({
                  content: contentString,
                  backgroundColor: "#eee",
                  borderColor: "lightgrey",
                  borderWidth: 2,

                 });


               naver.maps.Event.addListener(marker, 'click',function(e) {


                    if (infoWindow2.getMap()) {
                        infoWindow2.close();
                    } else {
                        infoWindow2.open(map, marker);
                    }
                });
            })

      <% end %>



      </script>

    </div>

</div>
</div>

</body>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="/assets/header.css.scss"> 

<header class="navbar navbar-dark bg-pink navbar-expand-lg">
	<div class="container-fluid dahong-container">
		
		<!-- Back 화살표 디자인 -->
		<div class="arrow-left">
			<%= link_to :back do %>
				<i class="fas fa-arrow-left"></i>
			<% end %>
		</div>
		
		<!-- global navbar 의 중앙 로고 담당 -->
		
		<div class="navbar-brand">
			<%= link_to root_path, id: 'logo', class: 'mx-auto' do %>
				<div class="logo_text">ㄷㅎ</div>
			<% end %>
		</div>
			
		
		<!-- Navbar의 우측 토글러 -->
   	<div class="dropdown dahong-dropdown">
   		
		  <button class="btn dahong-color dahong-gnb-dropdown-btn" type="button" id="nav_toggler" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    <span class="navbar-toggler-icon navbar-toggler-sizing "></span>
		  </button>
		  
		  <div class="dropdown-menu dropdown-menu-right dahong-color dahong-gnb-dropdown" aria-labelledby="dropdownMenu2">
		  
		  	<!--
		  	<li class="nav-item"><div class="nav_item">
		  		-->

			  	<!--
			  </div></li>
			  	-->
			  <!--link_to tag내부에 클래스  class: 'nav-link active' 들어가 있었음-->
		  
		    
		    	
		   	<% if user_signed_in? %>
		   <!--로그인 되었을 때: 유저정보 수정칸+ 로그아웃 칸-->
			    <%= link_to edit_user_registration_url do %>
			      <button class="dropdown-item  dahong-font-k" type="button">나의 정보</button>
			    <%end%> 
					<%= link_to  destroy_user_session_path, method: :delete, data:{ confirm: "정말로 로그아웃 하시겠습니까?"} do %>
						<button class="dropdown-item dahong-font-k" type="button">로그아웃</button>
							<% end %>
			  <% else %>
			  <!--로그인되지 않은 상태: 로그인 하는 버튼-->
						<%= link_to  new_user_session_url do %>
							<button class="dropdown-item dahong-font-k" type="button"> 로그인 </button>
						<% end %>
			  <% end %>		   
			  
			  	<% if user_signed_in? %>
		    	<!--로그인 되었을 때: 점포 등록, 점포 정보 수정칸-->
		    		<%= link_to  new_store_url do %>
		    		  <button class="dropdown-item  dahong-font-k" type="button">가게 등록	</button>	
		    		 <% end %>
		    		 <!-- link_to edit_store_url do -->
		    		 <!-- <button class="dropdown-item dahong-font" type="button"> Store Info Edit </button>-->
		    		 <!-- end-->
		    	<% else %>
		    	<!--로그인되지 않은 상태: 로그인창으로-->
		    		<%= link_to  new_user_session_url, data:{ confirm: "로그인부터 해주세요"} do %> <button class="dropdown-item  dahong-font-k" type="button">가게 등록</button>	
		    		<% end %>
		    	<% end %>
		  </div>
		</div>

	
	
	 
		
		
	</div>
</header>

app/views/stores/index.html.erb
<link rel="stylesheet" href="/assets/store_index.css.scss"> 

<div class="dahong-map-list-title"><%= @category %></div>
<%= link_to home_map_url(store_category: @category) do %>
    <button class="dahong-map-list-change-btn">지도로 보기</button>
<% end %>

<div class="dahong-list-search-field">
<%= form_tag("/stores/result", method: "get") do %>
  
    <%= search_field(:store, :store_name) %>
  
  <%= submit_tag("Search") %>
<% end %>
 
 
 <% if flash[:fail] %>
   <%= flash[:fail] %></div>
  <% end %>
  
</div>


<div class="dahong-float-clear"></div>
<div class="dahong-map-list-wrap">
<div class="row dahong-map-list-row">
  
   <% @stores.each do |store| %>
    <div class="col-xl-4 col-md-6 col-12 dahong-list-component-layout ">
      <div class = "dahong-list-card-layout shadow lifted">
        <%= link_to  store_path(store) do %>
        <div class = "dahong-list-photo"><%= image_tag store.photo.url(:thumb) %></div>
        <div class = "dahong-list-storename" ><%= store.store_name %></div>
        <div class = "dahong-list-address"><%= store.address %></div>
        <div class = "dahong-list-contact"><%= store.contact %></div>
        <div class = "dahong-list-content"><%= store.short_content %></div>
   
        <% end %>
        
      </div>
    </div>
  <% end %>
   
</div>
</div>

app/views/stores/result.html.erb
<link rel="stylesheet" href="/assets/store_index.css.scss"> 

 
<div class="dahong-map-list-title"><%= @category %></div>
<%= link_to home_map_url(store_category: @category) do %>
    <button class="dahong-map-list-change-btn">지도로 보기</button>
<% end %>

<div class="dahong-list-search-field">
  <%= form_tag("/stores/result", method: "get") do %>
    
      <%= search_field(:store, :store_name) %>
    
    <%= submit_tag("Search") %>
  <% end %>
  
  <% if flash[:fail] %>
    <p style="
    text-align: center;
	  color: #ff5050;
	  font-weight: bold;
	  font-size: 2rem;
	  margin: 10%;
	  padding: 3%;"><%= flash[:fail] %></p>
  <% end %>
</div>
  
</div>


<div class="dahong-float-clear"></div>
<div class="dahong-map-list-wrap">
<div class="row dahong-map-list-row">
 
   <% @results.each do |store| %>
    <div class="col-xl-4 col-md-6 col-12 dahong-list-component-layout ">
      <div class = "dahong-list-card-layout shadow lifted">
        <%= link_to  store_path(store) do %>
        <div class = "dahong-list-photo"><%= image_tag store.photo.url(:thumb) %></div>
        <div class = "dahong-list-storename" ><%= store.store_name %></div>
        <div class = "dahong-list-address"><%= store.address %></div>
        <div class = "dahong-list-contact"><%= store.contact %></div>
        <div class = "dahong-list-content"><%= store.short_content %></div>
   
        <% end %>
        
      </div>
    </div>
  <% end %>
   
</div>
</div>

app/views/stores/show.html.erb
<head>
  <link rel="stylesheet" href="/assets/store_show.scss">   
  <link rel="stylesheet" href="/assets/store.scss">   
</head>

<body>
  <% if flash[:fail] %>
    <p style="
    text-align: center;
	  color: #ff5050;
	  font-weight: bold;
	  font-size: 2rem;
	  margin: 10%;
	  padding: 3%;"><%= flash[:fail] %></p>
  <% end %>
  <!--가게 이름-->
  <section class = 'StoreInfo_Title'>
    <div style="text-align: center; margin-bottom: 3%"> 
      <h2 class="dahong-store-show-store_name"><strong> <%= @store.store_name%> </strong></h2>
    </div>
  </section>
  
  <div class="container-fluid dahong-h-center" >
    <!--캐러셀(가게사진)-->
    <section class = 'StoreInfo_Photo'>
      <div id="myCarousel" class="carousel slide  dahong-h-center dahong-h-carousel" data-ride="carousel">
        <!-- 몇번째 사진인지 알려주는 indicator -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
    
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img class="dahong-h-c-image" src=<%= @store.photo%> >
          </div>
          <div class="item">
            <img class="dahong-h-c-image" src=<%= @store.photo2 %>>
          </div>
          <div class="item">
            <img class="dahong-h-c-image" src=<%= @store.photo3 %>>
          </div>
        </div>
        
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </section>        

        <!--가게 상세 설명이 들어갈 부분-->
        
    <section class = 'StoreInfo_Body'> 
      <div class="container fluid" style="margin-top: 3%; margin-bottom: 10%;">
          <div class="row">
           <div class="col dahong-show-col">
              <div class = "dahong-list-address"><p><strong>주소</strong></p></div>
          </div>
          <div class="col-9 dahong-h-p">
            <%= @store.address %>
          </div>
        </div>
          <div class="row">
            <div class="col dahong-show-col">
              <div class = "dahong-list-contact"><p><strong>연락처</strong></div>
            </div>
          <div class="col-9 dahong-h-p">
            <a href="tel:<%= @store.contact %>"> <%= @store.contact %></a>
          </div>
        </div>
          <div class="row">
            <div class="col dahong-show-col">
              <div class = "dahong-list-content"><p><strong>한마디</strong></div>
            </div>
          <div class="col-9 dahong-h-p">
            <%= @store.short_content %>
          </div>
        </div>
          <div class="row">
            <div class="col dahong-show-col">
              <p class="dahong-show-detailcontent"><strong>소개글</strong></p>
            </div>
          <div class="col-9 dahong-h-p">
            <%= raw @store.detail_content %>
          </div>
        </div>
       
      </div>

        
      
    </section>
    
      
      

  </div>
       
        
  <div class="row row_for_show">
   
    <div class="col col_for_show">
      <%= link_to edit_store_path(@store) do %>
      <button class ="dahong-store-edit-btn"> 수정하기 </button> 
      <!--<button class ="btn btn-block"> 수정하기 </button> -->
    <% end %>
    </div>
     <div class="col col_for_show">
      <%= link_to store_path(@store), method: :delete, data: { confirm: '진삭?' } do %>
        <button class ="dahong-store-delete-btn"> 삭제하기 </button> 
        <!--<button class ="btn btn-block"> 삭제하기 </button> -->
      <% end %>
    </div>
  </div>
  
  <div id="h-footer">
    <p></p>
  </div>

</body>